### ISSUE TITLE
Carpet_Client with OptiFine crash 1.13.2

### ISSUE THREAD

**Issue by Shroototem** [gnembon/carpetmod#69]
When using 1.13.2 Carpet_Client and OptiFine_1.13.2_HD_U_E5 the game crashes on world load. This is just a part of the crash report. If need be I can upload the full one.

[10:53:27] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access field eq.n from class cwt
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_201]
	at k.a(Util.java:158) [k.class:?]
	at cft.c(Minecraft.java:855) [cft.class:?]
	at cft.a(Minecraft.java:379) [cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]

**Comment by gnembon** [comment]
Yeah, these jar mods are not meant to be used together. Its much better to run a local server with optifine client. I hope its not the installer that used optifine version to patch it. I assume you patched it yourself.

**Comment by Shroototem** [comment]
I used MultiMC with rift to run the mods.

**Comment by gnembon** [comment]
Woah, that was never intended to be used that way. This wasn't even developed for rift. I would be surprized if this worked at the first place.
